flowchart
    A("Start") --> B["Getal = Console.ReadLine"/]
    B --> C{"getal % 3 == 0 &&
    getal % 5 == 0"}
    C -- True --> D[/"Write FizzBuzz naar console"/]
    D --> O["End"]
    C -- False --> F{"getal % 3 == 0?"}
    F -- True --> G[/"Write Fizz naar console"/]
    G --> O
    F -- False --> I{"getal % 5 == 0?"}
    I -- True --> J[/"Write Buzz naar console"/]
    J --> O
    I -- False --> K[/"Write geen deling door 3 of 5 naar console"/]
    K --> O


flowchart
    A(Start)
    A --> C{getal1 > 0?}
    C --> |True| D[Voeg getal1 toe aan var som]
    C --> |False| F
    D --> F{getal2 > 0?}
    F --> |True| G[Voeg getal2 toe aan var som]
    F --> |False| I
    G --> I{getal3 > 0?}
    I --> |True| J[Voeg getal3 toe aan var som]
    I --> |False| L
    J --> L{getal4 > 0?}
    L --> |True| M[Voeg getal4 toe aan var som] 
    M --> N[Toon som]
    L --> |False| N
    N --> O[End]