# Grype configuration for vulnerability scanning
# Ignore vulnerabilities in npm's own bundled dependencies (part of Node.js installation)
# These are system-level packages we cannot control

ignore:
  # Ignore vulnerabilities in npm's internal dependencies
  - vulnerability: "*"
    package:
      name: glob
      type: npm
      location: /usr/local/lib/node_modules/npm/**
    
  - vulnerability: "*"
    package:
      name: tar
      type: npm
      location: /usr/local/lib/node_modules/npm/**
    
  - vulnerability: "*"
    package:
      name: diff
      type: npm
      location: /usr/local/lib/node_modules/npm/**

  # Alpine system vulnerabilities with no fix available
  # These are tracked upstream but don't affect our application
  - vulnerability: CVE-2026-22184  # zlib - no fix available, affects untgz utility only
    package:
      name: zlib
      type: apk
      
  - vulnerability: CVE-2025-60876  # busybox wget - low risk for container environment
    package:
      name: busybox*
      type: apk
