using TMPro;
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections.Generic;

public class EnvironmentSystem : MonoBehaviour
{
    //[Header("Prefab Linking")]
    //public GameObject circlePrefab;
    //public GameObject squarePrefab;
    //public GameObject trianglePrefab;

    [Header("UI References")]
    public TMP_Text UserMessage;
    public TMP_InputField envName;
    public TMP_InputField envMaxHeight;
    public TMP_InputField envMaxLength;
    public UnityEngine.UIElements.ScrollView loadEnvironment;
    [SerializeField] private Transform contentPanel;
    [SerializeField] private GameObject environmentButtonPrefab;

    [Header("Dependencies")]
    private UserApiClient userApiClient;
    private Object2DApiClient object2DApiClient;
    private Environment2DApiClient enviroment2DApiClient;
    
    private List<Environment2D> environmentList;
    //private Environment2D loadedEnvironment;

    private void Start()
    {
        // Fetch the API client references from the manager's singleton
        userApiClient = ApiClientManager.Instance.UserApiClient;
        object2DApiClient = ApiClientManager.Instance.Object2DApiClient;
        enviroment2DApiClient = ApiClientManager.Instance.Environment2DApiClient;

        // Read Environments and fill UI scrollview
        ReadEnvironments(true);
    }

    #region UI Methodes

    public void ShowExistingEnvironmentsInUI()
    {
        // Clear existing items.
        foreach (Transform child in contentPanel)
        {
            Destroy(child.gameObject);
        }

        foreach (var item in environmentList)
        {
            // Instantiate a new button for each environment.
            GameObject buttonObj = Instantiate(environmentButtonPrefab, contentPanel);
            Button button = buttonObj.GetComponent<Button>();

            // Set the button's text to the environment name.
            TextMeshProUGUI buttonText = buttonObj.GetComponentInChildren<TextMeshProUGUI>();
            if (buttonText != null)
            {
                buttonText.text = item.name;
            }

            string environmentId = item.id; // Use a local copy of the environment ID for the listener (to avoid closure issues).
            
            // Set the button's event listener to call methode with environmentId embedded.
            button.onClick.AddListener(() => {
                LoadEnvironment(environmentId); 
            });
        }
    }

    #endregion UI Methodes


    #region Environment

    public async void CreateEnvironment2D()
    {
        var newEnvironement = new Environment2D
        {
            // Generated by Server
            id = string.Empty,

            // Get values from the input fields
            name = envName.text,
            maxHeight = Convert.ToInt32(envMaxHeight.text),
            maxLength = Convert.ToInt32(envMaxLength.text),

        };

        IWebRequestReponse webRequestResponse = await enviroment2DApiClient.CreateEnvironment(newEnvironement);

        switch (webRequestResponse)
        {
            case WebRequestData<Environment2D> dataResponse:
                // TODO: Handle succes scenario.
                newEnvironement.id = dataResponse.Data.id;
                UserMessage.color = Color.green;
                UserMessage.text = "Environment created succesfully!";
                LoadEnvironment(newEnvironement.id);

                break;
            case WebRequestError errorResponse:
                // TODO: Handle error scenario. Show the errormessage to the user.
                string errorMessage = errorResponse.ErrorMessage;
                Debug.Log("Create environment2D error: " + errorMessage);
                UserMessage.color = Color.green;
                UserMessage.text = errorMessage;
                break;
            default:
                throw new NotImplementedException("No implementation for webRequestResponse of class: " + webRequestResponse.GetType());
        }
    }

    public async void ReadEnvironments(bool showInUI = false)
    {
        IWebRequestReponse webRequestResponse = await enviroment2DApiClient.ReadEnvironment2Ds();

        switch (webRequestResponse)
        {
            case WebRequestData<List<Environment2D>> dataResponse:
                {
                    environmentList = dataResponse.Data;
                    // TODO: Handle succes scenario.
                    if (showInUI)
                    {
                        ShowExistingEnvironmentsInUI();
                    }
                    break;
                }
            case WebRequestError errorResponse:
                {
                    string errorMessage = errorResponse.ErrorMessage;
                    // TODO: Handle error scenario. Show the errormessage to the user.
                    UserMessage.color = Color.red;
                    UserMessage.text = errorMessage;
                    break;
                }
            default:
                {
                    throw new NotImplementedException("No implementation for webRequestResponse of class: " + webRequestResponse.GetType());
                }
        }
    }

    public void LoadEnvironment(string environmentId)
    {
        Debug.Log($"Loaded environment {environmentId}");
        //TODO Some magic
        //loadedEnvironment = null; // TODO make get list entry
        //ReadObjects();
    }

    //public async void DeleteEnvironments()
    //{
    //    IWebRequestReponse webRequestResponse = await enviroment2DApiClient.DeleteEnvironment(loadedEnvironment.id);

    //    switch (webRequestResponse)
    //    {
    //        case WebRequestData<string> dataResponse:
    //            string responseData = dataResponse.Data;
    //            // TODO: Handle succes scenario.
    //            break;
    //        case WebRequestError errorResponse:
    //            string errorMessage = errorResponse.ErrorMessage;
    //            Debug.Log("Delete environment error: " + errorMessage);
    //            // TODO: Handle error scenario. Show the errormessage to the user.
    //            break;
    //        default:
    //            throw new NotImplementedException("No implementation for webRequestResponse of class: " + webRequestResponse.GetType());
    //    }
    //}

    #endregion Environment

    #region Object2D

    //public async void ReadObjects()
    //{
    //    IWebRequestReponse webRequestResponse = await object2DApiClient.ReadObject2Ds(object2D.environmentId);

    //    switch (webRequestResponse)
    //    {
    //        case WebRequestData<List<Object2D>> dataResponse:
    //            List<Object2D> object2Ds = dataResponse.Data;
    //            Debug.Log("List of object2Ds: " + object2Ds);
    //            object2Ds.ForEach(object2D => Debug.Log(object2D.id));
    //            GameObject prefabToInstantiate;
    //            // TODO: Succes scenario. Show the enviroments in the UI

    //            foreach (var item in object2Ds)
    //            {
    //                prefabToInstantiate = null;

    //                switch (item.prefabId)
    //                {
    //                    case "Circle":
    //                        prefabToInstantiate = circlePrefab;
    //                        break;
    //                    case "Square":
    //                        prefabToInstantiate = squarePrefab;
    //                        break;
    //                    case "Triangle":
    //                        prefabToInstantiate = trianglePrefab;
    //                        break;
    //                    default:
    //                        Debug.LogWarning($"Unknown prefab ID: {item.prefabId}");
    //                        continue;
    //                }

    //                if (prefabToInstantiate != null)
    //                {
    //                    // Convert item properties (Position, Scale and Rotation) to Unity types
    //                    Vector2 position = new(item.positionX, item.positionY);
    //                    Quaternion rotation = Quaternion.Euler(0f, 0f, item.rotationZ);
    //                    Vector2 scale = new(item.scaleX, item.scaleY);

    //                    // Spawn Object and assert scale
    //                    GameObject spawnedObject = Instantiate(prefabToInstantiate, position, rotation);
    //                    spawnedObject.transform.localScale = scale;

    //                    // Get SpriteRenderer and assert SortingLayer
    //                    spawnedObject.GetComponent<SpriteRenderer>().sortingOrder = item.sortingLayer;
    //                }

    //                // TODO Remove existing objects

    //            }
    //            break;

    //        case WebRequestError errorResponse:
    //            string errorMessage = errorResponse.ErrorMessage;
    //            Debug.Log("Read object2Ds error: " + errorMessage);
    //            // TODO: Error scenario. Show the errormessage to the user.
    //            break;

    //        default:
    //            throw new NotImplementedException("No implementation for webRequestResponse of class: " + webRequestResponse.GetType());
    //    }
    //}

    //public async void CreateObject2D()
    //{
    //    IWebRequestReponse webRequestResponse = await object2DApiClient.CreateObject2D(object2D);

    //    switch (webRequestResponse)
    //    {
    //        case WebRequestData<Object2D> dataResponse:
    //            object2D.id = dataResponse.Data.id;
    //            // TODO: Handle succes scenario.
    //            break;
    //        case WebRequestError errorResponse:
    //            string errorMessage = errorResponse.ErrorMessage;
    //            Debug.Log("Create Object2D error: " + errorMessage);
    //            // TODO: Handle error scenario. Show the errormessage to the user.
    //            break;
    //        default:
    //            throw new NotImplementedException("No implementation for webRequestResponse of class: " + webRequestResponse.GetType());
    //    }
    //}

    //public async void UpdateObject2D()
    //{
    //    IWebRequestReponse webRequestResponse = await object2DApiClient.UpdateObject2D(object2D);

    //    switch (webRequestResponse)
    //    {
    //        case WebRequestData<string> dataResponse:
    //            string responseData = dataResponse.Data;
    //            // TODO: Handle succes scenario.
    //            break;
    //        case WebRequestError errorResponse:
    //            string errorMessage = errorResponse.ErrorMessage;
    //            Debug.Log("Update object2D error: " + errorMessage);
    //            // TODO: Handle error scenario. Show the errormessage to the user.
    //            break;
    //        default:
    //            throw new NotImplementedException("No implementation for webRequestResponse of class: " + webRequestResponse.GetType());
    //    }
    //}

    #endregion

}
