name: L1Q3-LU2 WebApi Deploy

env:
  ARTIFACT_NAME: WebApi
  DOTNET_CORE_VERSION: 9.0.x
  PUBLISH_DIRECTORY: "./out/publish"
on:
  push:
    branches:
      - main
      - deployment 
  workflow_dispatch:

jobs:
  check:
      runs-on: ubuntu-latest
      steps:
        - name: "Check if AZURE_WEBAPP_NAME secret exists"
          env: 
            super_secret: ${{ secrets.L1Q3_WEBAPI_PROJECT_NAME }}
          if: ${{ env.super_secret == '' }}
          run: 'echo "echo the secret \"AZURE_WEBAPP_NAME\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions\" to create it"; exit 1;'
    
        - name: "Check if AZURE_WEBAPP_PUBLISH_PASSWORD secret exists"
          env: 
            super_secret: ${{ secrets.L1Q3_AZURE_WEBAPP_PUBLISH_USERNAME }}
          if: ${{ env.super_secret == '' }}
          run: 'echo "echo the secret \"AZURE_WEBAPP_PUBLISH_PASSWORD\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions \" to create it"; exit 1;'
    
        - name: "Check if AZURE_WEBAPP_PUBLISH_USERNAME secret exists"
          env: 
            super_secret: ${{ secrets.L1Q3_AZURE_WEBAPP_PUBLISH_PASSWORD }}
          if: ${{ env.super_secret == '' }}
          run: 'echo "echo the secret \"AZURE_WEBAPP_PUBLISH_USERNAME\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions\" to create it"; exit 1;'
    
        - name: "Check if WEBAPI_PROJECT_NAME secret exists"
          env: 
            super_secret: ${{ secrets.L1Q3_AZURE_WEBAPP_NAME }}
          if: ${{ env.super_secret == '' }}
          run: 'echo "echo the secret \"WEBAPI_PROJECT_NAME\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions\" to create it"; exit 1;'
        
  build:

    runs-on: ubuntu-latest
    needs: check
    steps:
    
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.DOTNET_CORE_VERSION}}

    - name: Restore dependencies
      run: dotnet restore "Leerjaar 1/Q3 2D Graphics/LU2 - Minimal Viable Product/CoreLink/CoreLink.WebApi/CoreLink.WebApi.csproj"

    - name: Build
      run: dotnet build "Leerjaar 1/Q3 2D Graphics/LU2 - Minimal Viable Product/CoreLink/CoreLink.WebApi/CoreLink.WebApi.csproj" --no-restore

    - name: Test
      run: dotnet test "Leerjaar 1/Q3 2D Graphics/LU2 - Minimal Viable Product/CoreLink/CoreLink.WebApi/CoreLink.WebApi.csproj" --no-build --verbosity normal

    - name: Publish
      run: dotnet publish "Leerjaar 1/Q3 2D Graphics/LU2 - Minimal Viable Product/CoreLink/CoreLink.WebApi/CoreLink.WebApi.csproj" --output ${{env.PUBLISH_DIRECTORY}} --configuration Release
    
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.PUBLISH_DIRECTORY}}

  deploy:
    runs-on: ubuntu-latest
    needs: [check, build]
    steps:

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.PUBLISH_DIRECTORY}}

     # Deploy to Azure Web apps
    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ secrets.L1Q3_AZURE_WEBAPP_NAME }} # TODO May change to env.AZURE_WEBAPP_NAME
        publish-profile: <publishData><publishProfile profileName="${{secrets.L1Q3_AZURE_WEBAPP_NAME}} - Zip Deploy" publishMethod="ZipDeploy" publishUrl="${{ secrets.L1Q3_AZURE_WEBAPP_NAME }}.scm.azurewebsites.net:443" userName="${{ secrets.L1Q3_AZURE_WEBAPP_PUBLISH_USERNAME }}" userPWD="${{ secrets.L1Q3_AZURE_WEBAPP_PUBLISH_PASSWORD }}" destinationAppUrl="http://${{ secrets.L1Q3_AZURE_WEBAPP_NAME }}.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
        package: '${{ env.PUBLISH_DIRECTORY}}'